import { StyleSheet } from 'react-native';

import type { AppTheme } from '../../ui/theme';

export function createRequestStyles(theme: AppTheme) {
  return StyleSheet.create({
    header: {
      minHeight: 58,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 12,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: theme.colors.border,
    },
    backButton: { width: 42, height: 42, alignItems: 'center', justifyContent: 'center' },
    backGlyph: { fontSize: 36, lineHeight: 38, fontWeight: '300', color: theme.colors.secondary },
    headerTitle: { fontSize: 18, lineHeight: 22, fontWeight: '800', color: theme.colors.textPrimary },
    headerSpacer: { width: 42 },
    content: { paddingHorizontal: 18, paddingTop: 18, paddingBottom: 32, gap: 10 },
    accountLabel: { fontSize: 11, lineHeight: 15, color: theme.colors.textTertiary },
    addressBox: { borderRadius: 10, padding: 12, backgroundColor: theme.colors.surfaceMuted, gap: 4 },
    addressTitle: { fontSize: 10, lineHeight: 13, color: theme.colors.textTertiary, fontWeight: '800' },
    address: { fontSize: 11, lineHeight: 16, color: theme.colors.textPrimary, fontWeight: '600' },
    sectionLabel: { marginTop: 10, fontSize: 10, lineHeight: 13, color: theme.colors.textTertiary, fontWeight: '800' },
    assetList: { gap: 8, paddingVertical: 2 },
    assetButton: {
      minHeight: 48,
      minWidth: 104,
      borderRadius: 9,
      borderWidth: 1,
      borderColor: theme.colors.border,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 12,
      backgroundColor: theme.colors.surface,
    },
    assetButtonSelected: { borderColor: theme.colors.actionPrimary, backgroundColor: theme.colors.actionPrimarySubtle },
    assetText: { fontSize: 11, lineHeight: 15, color: theme.colors.textSecondary, fontWeight: '700' },
    assetTextSelected: { color: theme.colors.actionPrimary },
    assetIssuer: { fontSize: 9, lineHeight: 12, color: theme.colors.textTertiary },
    assetIssuerSelected: { color: theme.colors.actionPrimary },
    warning: { fontSize: 10, lineHeight: 15, color: theme.colors.warning },
    optionRow: { flexDirection: 'row', gap: 8, flexWrap: 'wrap' },
    optionButton: {
      minHeight: 36,
      borderRadius: 9,
      borderWidth: 1,
      borderColor: theme.colors.border,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 12,
      backgroundColor: theme.colors.surface,
    },
    optionButtonSelected: {
      borderColor: theme.colors.actionPrimary,
      backgroundColor: theme.colors.actionPrimarySubtle,
    },
    optionText: { fontSize: 11, lineHeight: 15, color: theme.colors.textSecondary, fontWeight: '700' },
    optionTextSelected: { color: theme.colors.actionPrimary },
    fieldBox: { minHeight: 52, borderRadius: 10, backgroundColor: theme.colors.surfaceMuted, paddingHorizontal: 14 },
    fieldInput: { minHeight: 52, color: theme.colors.textPrimary, fontSize: 14, paddingVertical: 0 },
    messageInput: {
      minHeight: 84,
      color: theme.colors.textPrimary,
      fontSize: 14,
      paddingTop: 12,
      textAlignVertical: 'top',
    },
    fieldHint: { fontSize: 9, lineHeight: 13, color: theme.colors.textTertiary },
    error: {
      borderRadius: 9,
      padding: 12,
      backgroundColor: theme.colors.negativeMuted,
      color: theme.colors.negative,
      fontSize: 11,
      lineHeight: 16,
    },
    status: {
      borderRadius: 9,
      padding: 12,
      backgroundColor: theme.colors.positiveMuted,
      color: theme.colors.positive,
      fontSize: 11,
      lineHeight: 16,
    },
    uriBox: { borderRadius: 10, backgroundColor: theme.colors.surfaceMuted, padding: 12, gap: 6 },
    uriLabel: { fontSize: 10, lineHeight: 13, color: theme.colors.textTertiary, fontWeight: '800' },
    uri: { fontSize: 10, lineHeight: 15, color: theme.colors.textSecondary },
    actions: { flexDirection: 'row', gap: 8, marginTop: 2 },
    actionButton: {
      flex: 1,
      minHeight: 44,
      borderRadius: 10,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.colors.actionPrimary,
    },
    secondaryActionButton: { backgroundColor: theme.colors.secondary },
    actionDisabled: { opacity: 0.45 },
    actionText: { fontSize: 12, lineHeight: 16, color: theme.colors.onActionPrimary, fontWeight: '800' },
    qrPanel: {
      marginTop: 4,
      borderRadius: 14,
      alignItems: 'center',
      padding: 18,
      backgroundColor: theme.colors.surface,
      borderWidth: 1,
      borderColor: theme.colors.border,
      gap: 12,
    },
    qrText: { fontSize: 9, lineHeight: 13, color: theme.colors.textSecondary, textAlign: 'center' },
    pressed: { opacity: 0.7 },
  });
}
