import { StyleSheet } from 'react-native';

import type { AppTheme } from '@ui/theme';

export function createManageAssetsStyles(theme: AppTheme) {
  return StyleSheet.create({
    safeArea: { flex: 1, backgroundColor: theme.colors.background },
    header: {
      minHeight: 58,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 12,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: theme.colors.border,
    },
    backButton: { width: 42, height: 42, alignItems: 'center', justifyContent: 'center' },
    backGlyph: { fontSize: 36, lineHeight: 38, fontWeight: '300', color: theme.colors.secondary },
    headerTitle: { fontSize: 18, lineHeight: 22, fontWeight: '800', color: theme.colors.textPrimary },
    headerSpacer: { width: 42 },
    manageContent: { paddingBottom: 36 },
    accountCaption: { paddingHorizontal: 18, paddingTop: 14, fontSize: 11, color: theme.colors.textTertiary },
    sectionLabel: {
      paddingHorizontal: 18,
      paddingTop: 22,
      paddingBottom: 8,
      fontSize: 10,
      lineHeight: 13,
      color: theme.colors.textTertiary,
      fontWeight: '800',
    },
    addBlock: { paddingHorizontal: 18, gap: 9 },
    input: {
      minHeight: 52,
      borderRadius: 10,
      backgroundColor: theme.colors.surfaceMuted,
      paddingHorizontal: 14,
      color: theme.colors.textPrimary,
      fontSize: 14,
    },
    issuerInput: { fontSize: 11, fontVariant: ['tabular-nums'] },
    helperText: { fontSize: 9, lineHeight: 14, color: theme.colors.textTertiary },
    primaryButton: {
      minHeight: 52,
      borderRadius: 10,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.colors.actionPrimary,
    },
    primaryButtonText: { fontSize: 14, color: theme.colors.onActionPrimary, fontWeight: '800' },
    disabled: { opacity: 0.45 },
    assetList: { borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: theme.colors.border },
    assetRow: {
      minHeight: 76,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 11,
      paddingHorizontal: 18,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: theme.colors.border,
    },
    assetIcon: {
      width: 40,
      height: 40,
      borderRadius: 20,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.colors.surfaceStrong,
    },
    assetIconText: { fontSize: 16, color: theme.colors.onSurfaceStrong, fontWeight: '800' },
    assetIdentity: { flex: 1, gap: 2 },
    assetCode: { fontSize: 14, lineHeight: 18, color: theme.colors.textPrimary, fontWeight: '800' },
    assetIssuer: { fontSize: 10, lineHeight: 13, color: theme.colors.textTertiary },
    balance: { fontSize: 10, lineHeight: 13, color: theme.colors.textSecondary },
    limitText: { fontSize: 10, lineHeight: 13, color: theme.colors.textSecondary },
    assetActions: { alignItems: 'stretch', gap: 6 },
    limitButton: {
      minWidth: 72,
      minHeight: 30,
      paddingVertical: 7,
      borderRadius: 15,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.colors.surfaceMuted,
      paddingHorizontal: 10,
    },
    limitButtonText: { fontSize: 10, color: theme.colors.secondary, fontWeight: '800' },
    removeButton: {
      minWidth: 64,
      minHeight: 32,
      paddingVertical: 7,
      borderRadius: 16,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.colors.surfaceMuted,
      paddingHorizontal: 10,
    },
    removeText: { fontSize: 10, color: theme.colors.negative, fontWeight: '800' },
    limitEditor: {
      paddingHorizontal: 18,
      paddingVertical: 14,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: theme.colors.border,
      backgroundColor: theme.colors.surfaceMuted,
      gap: 8,
    },
    limitEditorTitle: { fontSize: 12, lineHeight: 16, color: theme.colors.textPrimary, fontWeight: '800' },
    limitEditorMeta: { fontSize: 10, lineHeight: 14, color: theme.colors.textSecondary },
    limitEditorActions: { flexDirection: 'row', gap: 9 },
    cancelLimitButton: {
      flex: 1,
      minHeight: 44,
      borderRadius: 9,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.colors.surface,
    },
    cancelLimitText: { fontSize: 12, color: theme.colors.secondary, fontWeight: '800' },
    reviewLimitButton: {
      flex: 1,
      minHeight: 44,
      borderRadius: 9,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.colors.actionPrimary,
    },
    reviewLimitText: { fontSize: 12, color: theme.colors.onActionPrimary, fontWeight: '800' },
    emptyAssets: { minHeight: 110, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 24, gap: 5 },
    emptyTitle: { fontSize: 14, color: theme.colors.textPrimary, fontWeight: '800' },
    emptyText: { fontSize: 10, lineHeight: 15, color: theme.colors.textSecondary, textAlign: 'center' },
    error: {
      marginHorizontal: 18,
      marginTop: 14,
      borderRadius: 9,
      padding: 12,
      backgroundColor: theme.colors.negativeMuted,
      color: theme.colors.negative,
      fontSize: 11,
      lineHeight: 16,
    },
    reviewContent: { paddingBottom: 28 },
    reviewHero: { alignItems: 'center', paddingHorizontal: 22, paddingTop: 28, paddingBottom: 24, gap: 6 },
    assetHeroIcon: {
      width: 60,
      height: 60,
      borderRadius: 30,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.colors.surfaceStrong,
      marginBottom: 5,
    },
    assetHeroGlyph: { fontSize: 25, color: theme.colors.onSurfaceStrong, fontWeight: '800' },
    reviewAction: {
      fontSize: 9,
      lineHeight: 12,
      color: theme.colors.textTertiary,
      fontWeight: '800',
      letterSpacing: 0.7,
    },
    reviewAsset: { fontSize: 24, lineHeight: 29, color: theme.colors.textPrimary, fontWeight: '800' },
    reviewIssuer: { fontSize: 10, lineHeight: 14, color: theme.colors.textSecondary, textAlign: 'center' },
    rows: { borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: theme.colors.border },
    reviewRow: {
      minHeight: 56,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 18,
      paddingHorizontal: 18,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: theme.colors.border,
    },
    reviewLabel: { fontSize: 12, lineHeight: 16, color: theme.colors.textSecondary, fontWeight: '600' },
    reviewValue: {
      flex: 1,
      fontSize: 12,
      lineHeight: 16,
      color: theme.colors.textPrimary,
      fontWeight: '600',
      textAlign: 'right',
    },
    mono: { fontSize: 10, lineHeight: 14, color: theme.colors.textSecondary, fontWeight: '400' },
    authNote: {
      marginHorizontal: 18,
      marginTop: 20,
      borderRadius: 11,
      backgroundColor: theme.colors.surfaceMuted,
      padding: 14,
      gap: 5,
    },
    authTitle: { fontSize: 12, lineHeight: 16, color: theme.colors.secondary, fontWeight: '800' },
    authText: { fontSize: 10, lineHeight: 15, color: theme.colors.textSecondary },
    passphraseBlock: { marginHorizontal: 18, marginTop: 18, gap: 7 },
    passphrasePrompt: { fontSize: 11, lineHeight: 16, color: theme.colors.textSecondary },
    fieldLabel: { paddingBottom: 7, fontSize: 10, lineHeight: 13, color: theme.colors.textTertiary, fontWeight: '800' },
    bottomBar: {
      paddingHorizontal: 18,
      paddingTop: 10,
      paddingBottom: 12,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: theme.colors.border,
      backgroundColor: theme.colors.surface,
    },
    resultContent: {
      flexGrow: 1,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 30,
      paddingVertical: 40,
      gap: 10,
    },
    resultIcon: {
      width: 78,
      height: 78,
      borderRadius: 39,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 7,
    },
    resultPositive: { backgroundColor: theme.colors.positive },
    resultNegative: { backgroundColor: theme.colors.negative },
    resultUncertain: { backgroundColor: theme.colors.warning },
    resultGlyph: { fontSize: 34, color: theme.colors.onActionPrimary, fontWeight: '800' },
    resultTitle: {
      fontSize: 21,
      lineHeight: 26,
      color: theme.colors.textPrimary,
      fontWeight: '800',
      textAlign: 'center',
    },
    resultDescription: { fontSize: 12, lineHeight: 18, color: theme.colors.textSecondary, textAlign: 'center' },
    messageBody: { flex: 1, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 34, gap: 10 },
    messageIcon: {
      width: 58,
      height: 58,
      borderRadius: 29,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.colors.surfaceMuted,
    },
    messageGlyph: { fontSize: 24, color: theme.colors.textSecondary, fontWeight: '800' },
    messageTitle: {
      fontSize: 18,
      lineHeight: 23,
      color: theme.colors.textPrimary,
      fontWeight: '800',
      textAlign: 'center',
    },
    messageText: { fontSize: 12, lineHeight: 18, color: theme.colors.textSecondary, textAlign: 'center' },
    messageAction: {
      minHeight: 44,
      marginTop: 6,
      borderRadius: 9,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.colors.actionPrimary,
      paddingHorizontal: 18,
      paddingVertical: 10,
    },
    messageActionText: { fontSize: 12, lineHeight: 16, color: theme.colors.onActionPrimary, fontWeight: '800' },
    pressed: { opacity: 0.68 },
  });
}
