import {StyleSheet} from 'react-native';

import type {AppTheme} from '@ui/theme';

export function createSendFormStyles(theme: AppTheme) {
  return StyleSheet.create({
    safeArea: {flex: 1, backgroundColor: theme.colors.background},
    header: {
      minHeight: 58,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 12,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: theme.colors.border,
    },
    backButton: {width: 42, height: 42, alignItems: 'center', justifyContent: 'center'},
    backGlyph: {fontSize: 36, lineHeight: 38, fontWeight: '300', color: theme.colors.secondary},
    headerTitle: {fontSize: 18, lineHeight: 22, fontWeight: '800', color: theme.colors.textPrimary},
    headerSpacer: {width: 42},
    content: {paddingBottom: 28},
    fromLabel: {paddingHorizontal: 18, paddingTop: 14, fontSize: 11, lineHeight: 15, color: theme.colors.textTertiary},
    sectionLabel: {
      paddingHorizontal: 18,
      paddingTop: 21,
      paddingBottom: 8,
      fontSize: 10,
      lineHeight: 13,
      color: theme.colors.textTertiary,
      fontWeight: '800',
    },
    assetList: {paddingHorizontal: 18, gap: 9},
    assetCard: {
      width: 94,
      minHeight: 100,
      borderWidth: 1,
      borderColor: theme.colors.border,
      borderRadius: 12,
      padding: 11,
      backgroundColor: theme.colors.surface,
      gap: 5,
    },
    assetCardSelected: {borderColor: theme.colors.actionPrimary, backgroundColor: theme.colors.actionPrimarySubtle},
    assetIcon: {
      width: 32,
      height: 32,
      borderRadius: 16,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.colors.surfaceMuted,
    },
    assetIconSelected: {backgroundColor: theme.colors.actionPrimary},
    assetIconText: {fontSize: 14, color: theme.colors.secondary, fontWeight: '800'},
    assetIconTextSelected: {color: theme.colors.onActionPrimary},
    assetCode: {fontSize: 13, lineHeight: 16, color: theme.colors.textPrimary, fontWeight: '800'},
    assetBalance: {fontSize: 10, lineHeight: 13, color: theme.colors.textSecondary},
    balanceLine: {
      minHeight: 42,
      marginHorizontal: 18,
      marginTop: 10,
      paddingHorizontal: 12,
      borderRadius: 9,
      backgroundColor: theme.colors.surfaceMuted,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    balanceLabel: {fontSize: 11, color: theme.colors.textSecondary},
    balanceValue: {fontSize: 11, color: theme.colors.secondary, fontWeight: '700'},
    fieldBox: {
      minHeight: 52,
      marginHorizontal: 18,
      borderRadius: 10,
      backgroundColor: theme.colors.surfaceMuted,
      flexDirection: 'row',
      alignItems: 'center',
      paddingLeft: 14,
    },
    fieldInput: {flex: 1, minHeight: 52, color: theme.colors.textPrimary, fontSize: 14, paddingVertical: 0},
    fieldAction: {width: 45, height: 52, alignItems: 'center', justifyContent: 'center'},
    fieldActionGlyph: {fontSize: 18, color: theme.colors.textSecondary},
    fieldHint: {paddingHorizontal: 22, paddingTop: 5, fontSize: 9, lineHeight: 13, color: theme.colors.textTertiary},
    memoTypeRow: {flexDirection: 'row', gap: 8, paddingHorizontal: 18, paddingBottom: 8},
    memoTypeButton: {
      minHeight: 36,
      minWidth: 64,
      paddingHorizontal: 12,
      borderRadius: 9,
      borderWidth: 1,
      borderColor: theme.colors.border,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.colors.surface,
    },
    memoTypeButtonSelected: {
      borderColor: theme.colors.actionPrimary,
      backgroundColor: theme.colors.actionPrimarySubtle,
    },
    memoTypeText: {fontSize: 11, color: theme.colors.textSecondary, fontWeight: '700'},
    memoTypeTextSelected: {color: theme.colors.actionPrimary},
    amountBox: {
      minHeight: 70,
      marginHorizontal: 18,
      borderRadius: 10,
      backgroundColor: theme.colors.surfaceMuted,
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 14,
      gap: 10,
    },
    amountInput: {
      flex: 1,
      minHeight: 70,
      color: theme.colors.textPrimary,
      fontSize: 30,
      lineHeight: 36,
      fontWeight: '600',
      paddingVertical: 0,
    },
    amountAsset: {fontSize: 15, color: theme.colors.secondary, fontWeight: '800'},
    error: {
      marginHorizontal: 18,
      marginTop: 16,
      borderRadius: 9,
      padding: 12,
      backgroundColor: theme.colors.negativeMuted,
      color: theme.colors.negative,
      fontSize: 11,
      lineHeight: 16,
    },
    bottomBar: {
      paddingHorizontal: 18,
      paddingTop: 10,
      paddingBottom: 12,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: theme.colors.border,
      backgroundColor: theme.colors.surface,
    },
    reviewButton: {
      minHeight: 54,
      borderRadius: 11,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.colors.actionPrimary,
    },
    reviewButtonDisabled: {opacity: 0.5},
    reviewButtonText: {fontSize: 15, color: theme.colors.onActionPrimary, fontWeight: '800'},
    pressed: {opacity: 0.68},
  });
}

export function createSendReviewStyles(theme: AppTheme) {
  return StyleSheet.create({
    safeArea: {flex: 1, backgroundColor: theme.colors.background},
    header: {
      minHeight: 58,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 12,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: theme.colors.border,
    },
    backButton: {width: 42, height: 42, alignItems: 'center', justifyContent: 'center'},
    backGlyph: {fontSize: 36, lineHeight: 38, fontWeight: '300', color: theme.colors.secondary},
    headerTitle: {fontSize: 18, lineHeight: 22, fontWeight: '800', color: theme.colors.textPrimary},
    headerSpacer: {width: 42},
    content: {paddingBottom: 28},
    summaryHero: {alignItems: 'center', paddingHorizontal: 20, paddingTop: 28, paddingBottom: 24},
    summaryEyebrow: {
      fontSize: 10,
      lineHeight: 13,
      color: theme.colors.textTertiary,
      fontWeight: '800',
      letterSpacing: 0.8,
    },
    summaryAmount: {fontSize: 36, lineHeight: 44, color: theme.colors.textPrimary, fontWeight: '700', marginTop: 5},
    summaryAsset: {
      fontSize: 13,
      lineHeight: 17,
      color: theme.colors.textSecondary,
      fontWeight: '700',
      marginTop: 2,
      textAlign: 'center',
    },
    rows: {borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: theme.colors.border},
    reviewRow: {
      minHeight: 56,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 18,
      paddingHorizontal: 18,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: theme.colors.border,
    },
    label: {fontSize: 12, lineHeight: 16, color: theme.colors.textSecondary, fontWeight: '600'},
    value: {
      flex: 1,
      fontSize: 12,
      lineHeight: 16,
      color: theme.colors.textPrimary,
      fontWeight: '600',
      textAlign: 'right',
    },
    mono: {fontSize: 10, lineHeight: 14, color: theme.colors.textSecondary, fontWeight: '400'},
    authorizationNote: {
      marginHorizontal: 18,
      marginTop: 20,
      borderRadius: 11,
      padding: 14,
      backgroundColor: theme.colors.surfaceMuted,
      gap: 5,
    },
    authorizationTitle: {fontSize: 12, lineHeight: 16, color: theme.colors.secondary, fontWeight: '800'},
    authorizationText: {fontSize: 10, lineHeight: 15, color: theme.colors.textSecondary},
    passphraseBlock: {
      marginHorizontal: 18,
      paddingTop: 12,
      paddingBottom: 2,
      gap: 7,
    },
    passphrasePrompt: {fontSize: 11, lineHeight: 16, color: theme.colors.textSecondary},
    passphraseLabel: {fontSize: 10, lineHeight: 13, color: theme.colors.textTertiary, fontWeight: '800'},
    passphraseInput: {
      minHeight: 52,
      borderRadius: 10,
      backgroundColor: theme.colors.surfaceMuted,
      paddingHorizontal: 14,
      color: theme.colors.textPrimary,
      fontSize: 14,
    },
    error: {
      marginHorizontal: 18,
      marginTop: 14,
      borderRadius: 9,
      padding: 12,
      backgroundColor: theme.colors.negativeMuted,
      color: theme.colors.negative,
      fontSize: 11,
      lineHeight: 16,
    },
    bottomBar: {
      paddingHorizontal: 18,
      paddingTop: 10,
      paddingBottom: 12,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: theme.colors.border,
      backgroundColor: theme.colors.surface,
    },
  });
}
