import { StyleSheet } from 'react-native';

import type { AppTheme } from '@ui/theme';

export function createStyles(theme: AppTheme) {
  return StyleSheet.create({
    header: {
      minHeight: 58,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 12,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: theme.colors.border,
    },
    backButton: { width: 42, height: 42, alignItems: 'center', justifyContent: 'center' },
    backGlyph: { fontSize: 36, lineHeight: 38, fontWeight: '300', color: theme.colors.surfaceStrong },
    title: { fontSize: 18, lineHeight: 22, fontWeight: '800', color: theme.colors.textPrimary },
    headerSpacer: { width: 42 },
    content: { paddingTop: 16, paddingBottom: 34 },
    description: {
      paddingHorizontal: 20,
      paddingBottom: 12,
      fontSize: 12,
      lineHeight: 16,
      color: theme.colors.textTertiary,
    },
    sortError: { marginHorizontal: 20, marginBottom: 12, fontSize: 12, lineHeight: 16, color: theme.colors.negative },
    accountGroup: { marginBottom: 12 },
    accountCard: {
      minHeight: 108,
      marginHorizontal: 20,
      borderWidth: 2,
      borderColor: theme.colors.border,
      borderRadius: 14,
      backgroundColor: theme.colors.surface,
      paddingHorizontal: 14,
      paddingVertical: 12,
      gap: 6,
    },
    accountCardHidden: { opacity: 0.58 },
    accountTopRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 10 },
    accountIdentity: { flex: 1, gap: 7 },
    accountLabel: { fontSize: 16, lineHeight: 20, color: theme.colors.textPrimary, fontWeight: '800' },
    badges: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
    accessBadge: {
      paddingHorizontal: 8,
      paddingVertical: 3,
      borderRadius: 10,
      backgroundColor: theme.colors.actionPrimaryMuted,
    },
    accessBadgeText: { fontSize: 9, lineHeight: 12, fontWeight: '800', color: theme.colors.actionPrimaryPressed },
    hiddenBadge: {
      paddingHorizontal: 8,
      paddingVertical: 3,
      borderRadius: 10,
      backgroundColor: theme.colors.surfaceMuted,
    },
    hiddenBadgeText: { fontSize: 9, lineHeight: 12, fontWeight: '800', color: theme.colors.textSecondary },
    chevron: { fontSize: 28, lineHeight: 30, color: theme.colors.textTertiary, fontWeight: '300' },
    address: { fontSize: 11, lineHeight: 15, color: theme.colors.textSecondary, fontVariant: ['tabular-nums'] },
    network: { fontSize: 10, lineHeight: 13, color: theme.colors.textTertiary },
    sortControls: { flexDirection: 'row', gap: 8, marginHorizontal: 20, marginTop: 6 },
    sortButton: {
      minHeight: 38,
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.border,
      borderRadius: 10,
      backgroundColor: theme.colors.surface,
    },
    sortButtonDisabled: { opacity: 0.45, backgroundColor: theme.colors.surfaceMuted },
    sortButtonText: { fontSize: 12, lineHeight: 16, fontWeight: '700', color: theme.colors.textSecondary },
    sortButtonTextDisabled: { color: theme.colors.textTertiary },
    addButton: {
      minHeight: 64,
      marginHorizontal: 20,
      marginTop: 4,
      borderRadius: 12,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      backgroundColor: theme.colors.actionPrimary,
    },
    addIcon: { fontSize: 20, lineHeight: 22, color: theme.colors.onActionPrimary, fontWeight: '600' },
    addText: { fontSize: 15, lineHeight: 19, color: theme.colors.onActionPrimary, fontWeight: '800' },
    pressed: { opacity: 0.68 },
  });
}
